name: BigTreeMovies
favicon: null
layout_spectrum: 0.97011
typography_spectrum: 0.42663
title: Big Tree Productions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#5a5d94'
    - '#dbdbdb'
    - '#7b7b7b'
  brandStrength: 0.625
  lightness: 0.125
  saturation: 0.3125
  rhythmicContrast: 0.2808439936488867
purpose: []
